# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_auto_20160130_2154'),
        ('customer', '0005_merge'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('problem_description', models.CharField(max_length=400)),
                ('estimate_initial', models.FloatField(choices=[('3-Step Fuel System Service', 139.99), ('Synthetic Oil Change', 75.0), ('High Mileage Oil Change', 55.0), ('Star Service Oil Change', 39.99), ('Coolant Flush', 99.99), ('Transfer Case Service', 49.99), ('Differential Service', 49.99), ('Automatic Transmission Flush', 99.99), ('Wiper Blade Replacement, each', 8.99), ('Air Filter Replacement', 15.0), ('Cabin Air Filter Replacement', 19.99), ('Diagnosis', '105'), ('AC Service, excludes freon cost', 80.0)])),
                ('service_type', models.CharField(max_length=100)),
                ('estimate_revision', models.FloatField(blank=True)),
                ('hours_required', models.FloatField()),
                ('parts_require', models.CharField(blank=True, max_length=200)),
                ('estimate_approval', models.CharField(blank=True, max_length=100)),
                ('approval_date_time', models.DateTimeField(blank=True)),
                ('amount_paid', models.FloatField(blank=True)),
                ('date_completed', models.DateTimeField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle')),
            ],
            options={
                'db_table': 'CKTM_WORKORDER',
            },
        ),
    ]
