# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 21:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 9, 21, 17, 26, 337426, tzinfo=utc)),
        ),
    ]
