# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='service_type',
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_type',
            field=models.ManyToManyField(to='workorder.ServiceType'),
        ),
    ]
