# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 5, 21, 13, 30, 508613, tzinfo=utc)),
        ),
    ]
