# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20160309_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 11, 7, 33, 56, 412174, tzinfo=utc)),
        ),
    ]
