# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20160130_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='estimate_initial',
            field=models.IntegerField(),
        ),
    ]
