# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 01:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20160305_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 6, 1, 25, 11, 785423, tzinfo=utc)),
        ),
    ]
