# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 05:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20160306_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 5, 36, 24, 174646, tzinfo=utc)),
        ),
    ]
