# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0003_auto_20160130_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='estimate_initial',
            field=models.IntegerField(blank=True),
        ),
    ]
