# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 18:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20160307_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 18, 18, 22, 624927, tzinfo=utc)),
        ),
    ]
