# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20160311_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 12, 18, 4, 45, 495572, tzinfo=utc)),
        ),
    ]
