# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_auto_20160307_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 18, 25, 14, 187780, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='estimate_initial',
            field=models.FloatField(blank=True),
        ),
    ]
