# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0005_auto_20160312_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
