# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_auto_20160312_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
