# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_auto_20160307_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 7, 22, 31, 59, 88524, tzinfo=utc)),
        ),
    ]
