# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0007_auto_20160312_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'ordering': ['-date_created']},
        ),
    ]
