# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20160307_1825'),
        ('workorder', '0008_auto_20160307_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServiceNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_serviced', models.DateTimeField()),
                ('hours_spent', models.FloatField()),
                ('notes', models.CharField(max_length=400)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 5, 17, 19, 561211, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='employeeservicenotes',
            name='parts_used',
            field=models.ManyToManyField(blank=True, null=True, to='workorder.Part'),
        ),
        migrations.AddField(
            model_name='employeeservicenotes',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.WorkOrder'),
        ),
    ]
