# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_auto_20160308_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 8, 5, 17, 25, 673449, tzinfo=utc)),
        ),
    ]
