# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer_Adress',
            new_name='Customer_Address',
        ),
    ]
