# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
