# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-30 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_email'),
        ('customer', '0004_customer_address'),
    ]

    operations = [
    ]
