# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20160131_0820'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_address',
            table='CKTM_CUSTOMER_ADDRESS',
        ),
    ]
