# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-31 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20160131_0821'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer_address',
            table='CKTM_CUSTOMER_ADDRESSES',
        ),
    ]
