# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField(max_length=300)),
                ('posted', models.DateField(default=datetime.date(2016, 3, 7))),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'ordering': ['posted'],
                'db_table': 'CKTM_ANNOUNCEMENT',
            },
        ),
    ]
