# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 05:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='posted',
            field=models.DateField(default=datetime.date(2016, 3, 8)),
        ),
    ]
