# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
