# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('mgmt', 'Management'), ('admin', 'Administrative'), ('tech', 'Service Technician')], max_length=200),
        ),
    ]
