# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='ssn',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='employee',
            table='CKTM_EMPLOYEE',
        ),
    ]
