# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20160114_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=200, null=True, unique=True),
        ),
    ]
