# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
