# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20160115_2020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-job_title']},
        ),
    ]
