# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20160115_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('mgmt', 'Management'), ('admin', 'Administrative'), ('Service Technician', 'tech')], max_length=200),
        ),
    ]
